app/drivetracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("status.urls")),
    path("login/", include("login.urls")),
]

app/login/urls.py
from django.urls import path

from . import views

app_name = "login"

urlpatterns = [
    path("", views.LoginView.as_view(), name="login"),
]

app/status/urls.py
from django.urls import path

from . import views

app_name = "status"

urlpatterns = [
    path("", views.CarStatusView.as_view(), name="home"),
    path("status/", views.CarStatusAPIView.as_view(), name="statusAPI"),
    path("reservation/", views.ReservationView.as_view(), name="reservation"),
    path(
        "delete_reservation/<int:pk>/",
        views.DeleteReservationView.as_view(),
        name="delete_reservation",
    ),
    path("gasoline/", views.GasolineView.as_view(), name="gasoline"),
]

app/login/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    is_main = models.BooleanField(default=False)

    def __str__(self):
        return self.username

app/login/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django.forms import HiddenInput
from django.http import HttpResponse

from .models import CustomUser


class CustomLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        main_user = CustomUser.objects.filter(is_main=True).first()
        if main_user:
            self.fields["username"].initial = main_user.username
            self.fields["username"].widget = HiddenInput()
        else:
            HttpResponse("メインユーザーが存在しません")

app/login/views.py
from django.contrib.auth.views import LoginView

from .forms import CustomLoginForm

# 基本共用の一つのユーザーをみんなで使う


class LoginView(LoginView):
    template_name = "login.html"
    form_class = CustomLoginForm
    redirect_authenticated_user = True

app/templates/base.html
<!DOCTYPE html>

{% load static %}
{% load tz %}

<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
  <style>
    body {
      font-family: Arial, sans-serif;
    }

    .container {
      display: flex;
      justify-content: space-between;
      align-items: flex-end;
    }

    .left-section {
      display: flex;
      align-items: center;
      gap: 10px; /* アイテム間のスペース */
    }

    .left-section a {
      color: black;
      text-decoration: none;
    }

    .left-section h1 {
      margin-bottom: 0;
    }

    .right-section {
      display: flex;
      align-items: center;
      gap: 10px; /* アイテム間のスペース */
    }

    /* スマホ対応のメディアクエリ */
    @media (max-width: 600px) {
      .right-section {
        flex-direction: column;
        flex-wrap: wrap-reverse;
        align-items: flex-start;
        gap: 5px;
      }
    }
  </style>
    {% block extra_head %}{% endblock %}
</head>
<body>
  <div class="container">
    <div class="left-section">
      <h1><a href="javascript:toggleStatus()" id="status"></a></h1>
      <h1><a href="{% url 'status:reservation' %}" id="reservation-status"></a></h1>
    </div>
    <div class="right-section">
      <a href="{% url 'status:home' %}">ホーム</a>
      <a href="{% url 'status:reservation' %}">予約</a>
      <a href="{% url 'status:gasoline' %}">給油等</a>
      <a href="javascript:fetchStatusData();updateStatus()">更新</a>
    </div>
  </div>
  {% block content %}{% endblock %}
</body>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      fetchStatusData();

      // Fetch the current status data
      function fetchStatusData() {
        fetch("{% url 'status:statusAPI' %}")
          .then(response => response.json())
          .then(data => {
            updateStatus(data.is_using, data.is_reserved);
          })
          .catch(error => console.error('Error fetching status:', error));
      }

      // Update the displayed status and reservation information
      function updateStatus(isUsing, isReserved) {
        const statusElement = document.getElementById("status");
        const reservationElement = document.getElementById("reservation-status");

        if (isUsing) {
          statusElement.innerText = "使用中";
        } else {
          statusElement.innerText = "使用可能";
        }

        if (isReserved) {
          reservationElement.innerText = "(予約者あり)";
        } else {
          reservationElement.innerText = " ";
        }
      }

      // Toggle status with a POST request
      function toggleStatus() {
        fetch("{% url 'status:statusAPI' %}", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": "{{ csrf_token }}"
          },
          body: JSON.stringify({})
        })
        .then(fetchStatusData)
          .catch(error => console.error('Error toggling status:', error));
      }

      // onclickで呼び出せるように明示
      window.updateStatus = updateStatus;
      window.fetchStatusData = fetchStatusData;
      window.toggleStatus = toggleStatus;
    });
  </script>
</html>

app/templates/gasoline.html
{% extends "base.html" %}
{% block content %}
    <form method="post" action="{% url 'status:gasoline' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
<h1 style="display:inline;">給油履歴</h1>
<div style="overflow-x: auto;">
  <table style="min-width: 600px; width: 60%;">
    <thead>
      <tr>
        <th>給油した人</th>
        <th>金額</th>
        <th>備考</th>
        <th>記入日</th>
      </tr>
    </thead>
    <tbody>
      {% for gasoline in gasolines %}
      <tr>
        <td>{{ gasoline.name }}</td>
        <td>{{ gasoline.price }}</td>
        <td>
          <div style="max-width: 300px; overflow-wrap: break-word;">
          {{ gasoline.comment }}
          </div>
        </td>
        <td>{{ gasoline.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<p>車を使ってるときは使用中にしておいてください(文字をタップして切り替え)</p>
<div class="left-section">
  <h1><a href="{% url 'status:reservation' %}" id="reservation-status">予約一覧</a></h1>
</div>
<div style="overflow-x: auto;">
  <table style="min-width: 600px; width: 30%;">
    <thead>
      <tr>
        <th>開始時間</th>
        <th>終了時間</th>
        <th>予約した人</th>
        <th>passwordを入力して削除</th>
      </tr>
    </thead>
    <tbody>
      {% for reservation in reservations %}
      <tr>
        <td>{{ reservation.start_time|date:"m/d (D)" }}{{ reservation.start_time|time:"G:i" }}</td>
        <td>{{ reservation.end_time|date:"m/d (D)" }}{{ reservation.end_time|time:"G:i" }}</td>
        <td>{{ reservation.name }}</td>
        <td>
          <form method="post" action="{% url 'status:delete_reservation' reservation.id %}">
            {% csrf_token %}
            <input type="password" name="password" placeholder="パスワード" required>
            <button type="submit">削除</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<div class='left-section'>
  <h1><a href="{% url 'status:gasoline' %}">給油履歴</a></h1>
</div>
<div style="overflow-x: auto;">
  <table style="min-width: 500px; width: 30%;">
    <thead>
      <tr>
        <th>給油した人</th>
        <th>金額</th>
        <th>備考</th>
        <th>記入日</th>
      </tr>
    </thead>
    <tbody>
      {% for gasoline in gasolines %}
      <tr>
        <td>{{ gasoline.name }}</td>
        <td>{{ gasoline.price }}</td>
        <td>
            <div style="max-width: 100px; overflow: hidden; text-overflow: ellipsis;">
            {{ gasoline.comment }}
            </div>
        </td>
        <td>{{ gasoline.created_at }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
<h1>保険料支払い状況</h1>
<div>
<canvas id="myChart"></canvas>
</div>
<p>2024年6月分から月12270円</p>
<p>支払い状況が更新されてないときは連絡してください</p>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
  const contributers = JSON.parse('{{ insurance_contributers|safe }}');
  console.log(contributers);

  //支払いが多い順に並び替え
  contributers.sort((a, b) => b.total_paid - a.total_paid);

  const labels = contributers.map(item => item.name); // nameフィールドをラベルに使用
  const data = contributers.map(item => item.total_paid); // total_paidフィールドをデータに使用

  const ctx = document.getElementById('myChart');

  new Chart(ctx, {
    type: 'bar',
    data: {
      labels: labels,
      datasets: [{
        label: '保険料支払い額 (円)',
        data: data,
        borderWidth: 1
      }]
    },
    options: {
      indexAxis: 'y',
      scales: {
        x: {
          beginAtZero: true
        }
      }
    }
  });
</script>
<h1>掲示板</h1>
{% for announcement in announcements %}
<p>{{ announcement.content|linebreaksbr }}</p>
{% endfor %}
{% endblock %}

app/templates/login.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>

    <form method="post" action="{% url 'login:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>

app/templates/reservation.html
{% extends 'base.html' %}
{% block extra_head %}
<link href="https://cdn.jsdelivr.net/npm/@event-calendar/build@1.5.0/event-calendar.min.css" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container">
  {% if error_message %}
  <p style="color: red;">{{ error_message }}</p>
  {% endif %}
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.name.id_for_label }}">名前:(本名だめ)</label>
      {{ form.name }}
    </div>
    <div class="form-group">
      <label for="{{ form.password.id_for_label }}">削除用パスワード:</label>
      {{ form.password }}
    </div>
    <div class="form-group">
      <label for="{{ form.start_date.id_for_label }}">開始日時:</label>
      {{ form.start_date }}
    </div>
    <div class="form-group" style="display: inline-block;">
      <label for="{{ form.end_date.id_for_label }}">終了日時:</label>
      {{ form.end_date }}
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>

<div id="ec"></div>
<script src="https://cdn.jsdelivr.net/npm/@event-calendar/build@1.5.0/event-calendar.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dayjs@1.11.9/dayjs.min.js"></script>
<script>
  function createDate(Y, M, D, h, m) {
    const now = new Date();
    now.setFullYear(Y);
    now.setMonth(M - 1);
    now.setDate(D);
    now.setHours(h);
    now.setMinutes(m);
    now.setSeconds(0);
    return now;
  }

  const events = [];
  {% for event in events %}
  events.push({
    id: {{ forloop.counter }},
    start: createDate({{ event.start_year }}, {{ event.start_month }}, {{ event.start_day }}, {{ event.start_hour }}, {{ event.start_minute }}),
    end: createDate({{ event.end_year }}, {{ event.end_month }}, {{ event.end_day }}, {{ event.end_hour }}, {{ event.end_minute }}),
    title: '{{ event.title }}',
    startEditable: false,
    durationEditable : false,
    backgroundColor: 'red',
  });
  {% endfor %}

  // 初期イベント数
  const initialEventCount = events.length;

  function getOverlappingEvents(event) {
    // 対象とするイベントは初期イベント数のみ
    return ec.getEvents().filter(e => e.id != event.id && e.id <= initialEventCount && e.start < event.end && e.end > event.start);
  }

  function hasOverlappingEvents(event) {
    return getOverlappingEvents(event).length > 0;
  }

  function hasOtherOverlappingEvents(event) {
    return getOverlappingEvents(event).filter(e => e.id != event.id).length > 0
  }
  const view = 'timeGridWeek';
  const views = {
    timeGridWeek: {
      type: 'timeGridWeek',
      duration: { days: 4 },
      buttonText: 'Week',
    },
  };

  const ec = new EventCalendar(document.getElementById('ec'), {
    events,
    headerToolbar: {
      start: 'prev',
      center: 'title',
      end: 'next',
    },
    view,
    views,
    nowIndicator: true,
    selectable: true,
    longPressDelay: 200,
    select: function(event) {
      if (hasOverlappingEvents(event)) {
        ec.unselect();
        return;
      }
      addEvent(event);
    },
    eventDrop: function ({ event, revert }) {
      if (hasOtherOverlappingEvents(event)) {
        revert();
      } else {
        // formに日時をセット
        document.getElementById('start_date').value = dayjs(event.start).format('YYYY-MM-DD HH:mm');
        document.getElementById('end_date').value = dayjs(event.end).format('YYYY-MM-DD HH:mm');
      }
    },
    eventResize: function ({ event, revert }) {
      if (hasOtherOverlappingEvents(event)) {
        revert();
      } else {
        // formに日時をセット
        document.getElementById('start_date').value = dayjs(event.start).format('YYYY-MM-DD HH:mm');
        document.getElementById('end_date').value = dayjs(event.end).format('YYYY-MM-DD HH:mm');
      }
    },
  });
  function addEvent(event) {
    event.id = new Date().getTime();
    ec.addEvent(event);
    ec.unselect();
    // 現在のイベント数が初期イベント数＋2を超えた場合、最新のイベントを削除
    const currentEventCount = ec.getEvents().length;
    if (currentEventCount > initialEventCount + 1) {
      currentEventId = ec.getEvents()[currentEventCount - 2].id;
      ec.removeEventById(currentEventId);
    }
    // formに日時をセット
    document.getElementById('start_date').value = dayjs(event.start).format('YYYY-MM-DD HH:mm');
    document.getElementById('end_date').value = dayjs(event.end).format('YYYY-MM-DD HH:mm');
  }
</script>
{% endblock %}